title: Dice Roller
hero_image: images/banner.png
description: Create a web app to simulate dice rolls
version: 4
listed: false
copyedit: false
ingredient: false
last_tested: "2019-02-13"
steps:
  - title: Introduction
  - title: Roll one die
  - title: Make the die faces look authentic
  - title: Roll two dice
  - title: Roll n dice
  - title: Select individual dice
  - title: Reroll the unselected dice
  - title: Drop-down game instructions 
  - title: "Challenge: dice with more than six sides"
    challenge: true
